const DURATION = {
  THIRTY: 30,
  FORTYFIVE: 45,
  HOUR: 60,
  NINETY: 90,
};
const SERVICES = {
  FADE: 'Fade',
  CUT: 'Classic Cut',
  GROOM: 'Groom',
  SHAVE: 'Shave',
  DYE: 'Dye',
  KIDS: 'Kids',
  CONSULT: 'Consult',
};

export const SERVICE_TYPES = {
  [SERVICES.FADE]: DURATION.THIRTY,
  [SERVICES.CUT]: DURATION.FORTYFIVE,
  [SERVICES.GROOM]: DURATION.THIRTY,
  [SERVICES.SHAVE]: DURATION.THIRTY,
  [SERVICES.DYE]: DURATION.NINETY,
  [SERVICES.KIDS]: DURATION.HOUR,
  [SERVICES.CONSULT]: DURATION.THIRTY,
};
